const ERROR_DATA = 400;
const NOT_AUTH = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const DUBLICATION = 409;
const ERROR_SERVER = 500;

module.exports = {
  ERROR_DATA,
  NOT_AUTH,
  NOT_FOUND,
  ERROR_SERVER,
  FORBIDDEN,
  DUBLICATION,
};
